### ISSUE TITLE
AttributeError: 'ScheduledScan' object has no attribute 'site_name_id' in utility.py

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#186]
```none
2020-03-12 09:21:40,970 [MainThread  ] [ERROR] AttributeError: 'ScheduledScan' object has no attribute 'site_name_id'
Traceback (most recent call last):
  File "/home/scantron/master/.venv/lib/python3.6/site-packages/rq/worker.py", line 884, in perform_job
    rv = job.perform()
  File "/home/scantron/master/.venv/lib/python3.6/site-packages/rq/job.py", line 664, in perform
    self._result = self._execute()
  File "/home/scantron/master/.venv/lib/python3.6/site-packages/rq/job.py", line 670, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./utility.py", line 56, in process_scan_status_change
    site_id = scheduled_scan.site_name_id
AttributeError: 'ScheduledScan' object has no attribute 'site_name_id'
```

**Comment by derpadoo** [comment]
https://github.com/rackerlabs/scantron/pull/187
